// UI that is shared among all pages in the app. This is the root layout.

// It is used to set up the global styles, fonts, and other UI elements that
// are common across all pages.

// It is also used to wrap the app in context providers, such as the AuthContextProvider
// and AudioPlayerProvider.

import { Geist, Geist_Mono } from "next/font/google";
import "/styles/globals.css";
import "/styles/customize-progress-bar.css";
import { AuthContextProvider } from "../context/auth-context";
import { AudioPlayerProvider } from "../context/audio-player-context.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AudioPlayerProvider>{children}</AudioPlayerProvider>
        {/* <AuthContextProvider>{children}</AuthContextProvider> */}
      </body>
    </html>
  );
}
