// This file is the root layout.
// i.e. UI that is shared among ALL pages in the app.
// It is used to set up the global styles, fonts, and other UI elements that
// are common across all pages.
// It is also used to wrap the app in context providers, such as the AuthContextProvider
// and AudioPlayerProvider.
// Also wraps the app in an error boundary to catch client-side errors. (see error-boundary-client.jsx)
// https://nextjs.org/docs/app/api-reference/file-conventions/layout
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "/styles/globals.css";
import "/styles/customize-progress-bar.css";
import { Providers } from "./providers.jsx";
import { Box, Typography, Container } from "@mui/material";
import SignedInAs from "@/app/components/login/signed-in-as";
import { LogoutButton } from "@/app/components/login/logout-button";
import Navigation from "@/app/components/navigation/nav-bar.jsx";
import LoginPopup from "@/app/components/login/login-popup.jsx";
import ColorblindFilters from "@/app/components/settings/colorblind-filters.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <Providers>
          <Box
            sx={{
              backgroundColor: "#1e1e1e",
              color: "white",
              minHeight: "100vh",
              pb: "30vh",
              pt: 4,
              width: "100%",
            }}
          >
            <Container maxWidth="lg">
              <LoginPopup />
              <ColorblindFilters />
              {/* Header and Logout */}
              <Box
                display="flex"
                justifyContent="space-between"
                alignItems="center"
                mb={4}
              >
                <Link href="/" passHref>
                  <Typography
                    variant="h4"
                    fontWeight="bold"
                    sx={{
                      cursor: "pointer",
                      textDecoration: "none",
                      color: "white",
                    }}
                  >
                    TUTTi.
                  </Typography>
                </Link>
                <Box display="flex" alignItems="center" gap={2}>
                  <SignedInAs />
                  <LogoutButton />
                </Box>
              </Box>

              {/* Navigation Bar */}
              <Navigation />
              {children}
            </Container>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
