// UI that is shared among all pages in the app. This is the root layout.

// It is used to set up the global styles, fonts, and other UI elements that
// are common across all pages.

// It is also used to wrap the app in context providers, such as the AuthContextProvider
// and AudioPlayerProvider.

import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "/styles/globals.css";
import "/styles/customize-progress-bar.css";
import { AudioPlayerProvider } from "@/context/audio-player-context.jsx";
import { AuthContextProvider } from "@/context/auth-context.jsx";
import { Box } from "@mui/material";
import ClientErrorBoundary from "@/app/components/error-boundary-client.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

{
  /* <AuthContextProvider>
          <UserProvider>
            <AuthenticatedLayout>{children}</AuthenticatedLayout>
          </UserProvider>
        </AuthContextProvider> */
}
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <ClientErrorBoundary>
          <AudioPlayerProvider>
            <AuthContextProvider>
              <Box
                sx={{
                  bgcolor: "#1e1e1e",
                  color: "white",
                  minHeight: "100vh",
                }}
              >
                <nav style={{ marginBottom: '1rem' }}> 
                  <Link href="/spotify-test">
                    <button style={{ padding: '0.5rem 1rem', fontSize: '1rem' }}>
                      Test Spotify Connection
                    </button>
                  </Link>
                </nav>
                {children}
              </Box>
            </AuthContextProvider>
          </AudioPlayerProvider>
        </ClientErrorBoundary>
      </body>
    </html>
  );
}
